# Partition module configuration for namdevOS installer

efiSystemPartition: "/boot/efi"
efiSystemPartitionSize: 512M
efiSystemPartitionName: "EFI"

userSwapChoices:
    - none
    - small
    - suspend
    - file

drawNestedPartitions: false
alwaysShowPartitionLabels: true

defaultFileSystemType: "ext4"

availableFileSystemTypes:
    - ext4
    - btrfs
    - xfs
