# Unpackfs module configuration for namdevOS installer
# Defines the source filesystem to unpack to the target

unpack:
    - source: "/cdrom/casper/filesystem.squashfs"
      sourcefs: "squashfs"
      destination: ""
