# Welcome module configuration for namdevOS installer

showSupportUrl: true
showKnownIssuesUrl: true
showReleaseNotesUrl: true

requirements:
    requiredStorage:    15.0
    requiredRam:        2.0
    internetCheckUrl:   https://github.com
    check:
        - storage
        - ram
        - root
    required:
        - storage
        - ram
        - root

geoip:
    style: "none"
