[greeter]
background = /usr/share/backgrounds/namdevos/namdevos-default.svg
theme-name = Adwaita-dark
icon-theme-name = Papirus-Dark
font-name = Ubuntu 11
xft-antialias = true
xft-dpi = 96
xft-hintstyle = slight
xft-rgba = rgb
indicators = ~host;~spacer;~clock;~spacer;~session;~power
clock-format = %H:%M
position = 50%,center 50%,center
panel-position = top
user-background = false
