[greeter]
background = /usr/share/backgrounds/namdevos/namdevos-default.svg
theme-name = Adwaita-dark
icon-theme-name = Papirus-Dark
cursor-theme-name = Bibata-Modern-Classic
cursor-theme-size = 24
font-name = Inter 11
xft-antialias = true
xft-dpi = 96
xft-hintstyle = slight
xft-rgba = rgb
indicators = ~host;~spacer;~clock;~spacer;~session;~language;~power
clock-format = %A, %B %d   %H:%M
position = 50%,center 50%,center
panel-position = top
user-background = false
default-user-image = /usr/share/icons/namdevos/namdevos-logo.svg
screensaver-timeout = 300
active-monitor = #cursor
